#!/usr/bin/env bash
# Create the 7 Entra groups for the AKS lab.
# Outputs ~/workspace/tfvars/aks-lab-groups.env which other scripts source.
set -euo pipefail

OUT_DIR="${OUT_DIR:-$HOME/workspace/tfvars}"
mkdir -p "$OUT_DIR"
OUT_FILE="$OUT_DIR/aks-lab-groups.env"

GROUP_NAMES=(
  "aks-ops-admins"
  "aks-app-admins-frontend-nonprod"
  "aks-app-admins-frontend-prod"
  "aks-app-admins-api-nonprod"
  "aks-app-admins-api-prod"
  "aks-app-admins-data-nonprod"
  "aks-app-admins-data-prod"
)

echo "# Generated by setup-entra.sh on $(date -u +%FT%TZ)" > "$OUT_FILE"

for g in "${GROUP_NAMES[@]}"; do
  echo "→ ensuring group: $g"
  oid=$(az ad group show --group "$g" --query id -o tsv 2>/dev/null || true)
  if [[ -z "$oid" ]]; then
    oid=$(az ad group create --display-name "$g" --mail-nickname "$g" --query id -o tsv)
    echo "  created: $oid"
  else
    echo "  exists: $oid"
  fi
  var=$(echo "$g" | tr 'a-z-' 'A-Z_')
  echo "${var}_OID=$oid" >> "$OUT_FILE"
done

echo
echo "Written: $OUT_FILE"
cat "$OUT_FILE"
